# -*- mode: ruby -*-
# vi: set ft=ruby :
  
VAGRANTFILE_API_VERSION = "2"
  
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "f41-cloud-libvirt"
  config.vm.box_url = "https://gb.mirrors.cicku.me/fedora/linux/releases/41/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-libvirt-41-1.4.x86_64.vagrant.libvirt.box"

 config.vm.define "client" do |client|
   client.vm.box_check_update = false
#   client.vm.host_name = "client-dev.example.com"
   client.vm.hostname = "client"
   client.ssh.insert_key = false
   client.vm.provider :libvirt do |domain|
       domain.cpus = 1
       domain.memory = 765
      end
end

end
